[package]
name = "sage"
version = "0.7.0"
description = "A next generation Chia wallet."
authors = ["Rigidity <me@rigidnetwork.com>"]
license = "Apache-2.0"
repository = "https://github.com/rigidity/sage"
edition = "2021"

[lints]
workspace = true

[lib]
name = "sage_lib"
crate-type = ["cdylib", "rlib"]

[dependencies]
sage-api = { workspace = true }
sage-config = { workspace = true }
sage-database = { workspace = true }
sage-keychain = { workspace = true }
sage-wallet = { workspace = true }
serde = { workspace = true, features = ["derive"] }
 
bip39 = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
tokio = { workspace = true }
bincode = { workspace = true }
toml = { workspace = true, features = ["preserve_order"] }
indexmap = { workspace = true, features = ["serde"] }
hex = { workspace = true }
hex-literal = { workspace = true }
chia = { workspace = true }
chia-wallet-sdk = { workspace = true, features = ["rustls"] }
clvmr = { workspace = true }
itertools = { workspace = true }
sqlx = { workspace = true, features = ["sqlite", "runtime-tokio"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing-appender = { workspace = true }
log = { workspace = true }
bigdecimal = { workspace = true }
bech32 = { workspace = true }
base64 = { workspace = true } 
serde_json = { workspace = true, features = ["arbitrary_precision"] } 


[package.metadata.cargo-machete]
ignored = ["serde_json" ]