[workspace.package]
readme = "README.md"
keywords = ["chia", "wallet", "blockchain", "crypto"]
categories = ["cryptography::cryptocurrencies"]

[workspace]
members = ["src-tauri", "crates/*"]
resolver = "2"

[workspace.lints.rust]
rust_2018_idioms = { level = "deny", priority = -1 }
rust_2021_compatibility = { level = "deny", priority = -1 }
future_incompatible = { level = "deny", priority = -1 }
nonstandard_style = { level = "deny", priority = -1 }
unsafe_code = "deny"
non_ascii_idents = "deny"
unused_extern_crates = "deny"
trivial_numeric_casts = "deny"
unreachable_pub = "allow"
unreachable_code = "warn"
unreachable_patterns = "warn"
dead_code = "warn"
deprecated = "deny"
deprecated_in_future = "deny"
missing_debug_implementations = "warn"
missing_copy_implementations = "warn"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
cargo = { level = "allow", priority = -1 }
pedantic = { level = "warn", priority = -1 }
too_many_lines = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
module_name_repetitions = "allow"
multiple_crate_versions = "allow"
must_use_candidate = "allow"
similar_names = "allow"
used_underscore_binding = "allow"
unwrap_used = "warn"
wildcard_imports = "allow"
cast_possible_truncation = "allow"

[workspace.dependencies]
sage-api = { path = "./crates/sage-api" }
sage-config = { path = "./crates/sage-config" }
sage-database = { path = "./crates/sage-database" }
sage-keychain = { path = "./crates/sage-keychain" }
sage-wallet = { path = "./crates/sage-wallet" }

# Serialization
serde = "1.0.204"
serde_with = "3.9.0"
serde_json = "1.0.122"
bincode = "1.3.3"
toml = "0.8.19"
hex = "0.4.3"
bigdecimal = "0.4.5"
base64 = "0.22.1"
 

# Specta
specta = "2.0.0-rc.20"
specta-typescript = "0.0.7" 
tauri-specta = "2.0.0-rc.20"

# Chia
chia = "0.15.0"
clvmr = "0.9.0"
chia-wallet-sdk = { version = "0.19.0", features = ["rustls"] }
bip39 = "2.0.0"
bech32 = "0.9.1"

# Crypto
sha2 = "0.10.8"
rand = "0.8.5"
rand_chacha = "0.3.1"
aes-gcm = "0.10.3"
argon2 = "0.5.3"

# Async
tokio = "1.39.2"
futures-util = "0.3.30"
futures-lite = "2.3.0"
sqlx = "0.8.0"
reqwest = { version = "0.12.7", default-features = false }

# Utilities
indexmap = "2.3.0"
itertools = "0.13.0"
anyhow = "1.0.86"
thiserror = "1.0.63"
hex-literal = "0.4.1"
rayon = "1.10.0"
once_cell = "1.19.0"
num-traits = "0.2.19"

# Tracing
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tracing-appender = "0.2.3"
log = "0.4.22"
test-log = "0.2.16"

[patch.crates-io]
chia-wallet-sdk = { git = "https://github.com/xch-dev/chia-wallet-sdk", rev = "2cf81a1df37eaf94dda9fed74785f30ec24669f2" }
